name: sustainable_travel_app
description: A sustainable travel planning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core
  firebase_core: ^2.24.2
  
  # Authentication
  firebase_auth: ^4.13.2
  
  # Firestore Database
  cloud_firestore: ^4.14.0
  
  # Storage (for user profile pictures)
  firebase_storage: ^11.6.1
  
  # Google Sign-In
  google_sign_in: ^6.1.5
  
  # Facebook Login
  flutter_facebook_auth: ^5.0.0
  
  # For local data storage
  shared_preferences: ^2.2.2
  
  # For better state management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/electric_car.png